DESCRIPTION
NEWS.md
R/ATA_class.R
R/ATA_functions.R
R/runshiny.R
R/shadow_class.R
R/shadow_functions.R
cran-comments.md
inst/shiny/app.R
man/STA.Rd
man/createShadowTestConfig.Rd
man/createStaticTestConfig.Rd
vignettes/constraints.Rmd
vignettes/rsymphony.Rmd

* Fix where `gap_limit` was incorrectly being passed onto `SYMPHONY` solver in `ATA()` and `Shadow()`, instead of `gap_limit_abs`. The two gap limits use the same default values, so this should not affect the solutions.
* Fix where `gap_limit` was not being passed onto `GUROBI` solver in `ATA()` and `Shadow()`.
* Fix where `time_limit` was not being passed onto `GUROBI` solver in `Shadow()`.
* Fix where `time_limit` was incorrectly being passed in ms units to `GLPK` solver in `Shadow()`.
* Fix where a valid interval-based refresh policy was triggering an error in `Shadow()`.
* Prevent the Shiny app from crashing when running adaptive assembly with a set-based refresh policy on item pools without sets.

Fix gap limit parse logic

---

R/shadow_class.R
R/solver_functions.R
R/static_class.R
man/createShadowTestConfig.Rd
man/createStaticTestConfig.Rd

* add a new slot `retry` in `config_Shadow` and `config_Static`. This is the number of times to retry running the solver, if the solver returns no solution. The purpose of retrying is to verify that there is indeed no solution.

do runMIP again if errors

---

DESCRIPTION
R/import.R
R/solver_functions.R

- Fix the issue where if `gurobi` is installed, `roxygen2::roxygenize()` fails with the following error:
```
Error in methods::getMethod(name, eval(call$signature), where = env) :
no method found for function '[' and signature item_pool, numeric
Calls: suppressPackageStartupMessages ... object_from_call -> parser_setMethod -> <Anonymous>
Execution halted
Exited with status 1.
```
- Explicitly use the `LogToConsole` parameter in `gurobi` solver calls.

fix roxygenize error when gurobi is installed

---

DESCRIPTION
R/plot_functions.R
cran-comments.md
man/plot-methods.Rd
tests/testthat/test-gfi.R

This version addresses following issues.
* In `man/plot-methods.Rd`, links to `base::plot()` are replaced by links to `graphics::plot()` to resolve a WARNING that occurs in R-oldrel:
```
checking Rd cross-references ... WARNING
Missing link or links in documentation object 'plot-methods.Rd':
‘[base]{plot}’
```
The WARNING occurs because `base::plot()` does not exist in versions R 3.x.x.
* In clang-ASAN, gcc-ASAN, the use of 'lpsymphony' in tests was causing heap-buffer-overflow:
```
=================================================================
==3289600==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x62500034f018 at pc 0x000000448067 bp 0x7ffd335f7ee0 sp 0x7ffd335f76a0
READ of size 1096 at 0x62500034f018 thread T0
#0 0x448066 in memcpy …
```

TestDesign 1.2.1

---

DESCRIPTION
cran-comments.md
tests/testthat/test_excluding.R

* In clang-ASAN, gcc-ASAN, the use of 'lpsymphony' in tests was causing heap-buffer-overflow on CRAN:
```
=================================================================
==3289600==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x62500034f018 at pc 0x000000448067 bp 0x7ffd335f7ee0 sp 0x7ffd335f76a0
READ of size 1096 at 0x62500034f018 thread T0
#0 0x448066 in memcpy /data/gannet/ripley/Sources2/LLVM/11.0.0/llvm-project-11.0.0/compiler-rt/lib/asan/../sanitizer_common/sanitizer_common_interceptors.inc:808:5
#1 0x7fd0a93eac31 in sym_explicit_load_problem(SYM_ENVIRONMENT*, int, int, int*, int*, double*, double*, double*, char*, double*, double*, char*, double*, double*, char) (/lib64/libSym.so.3+0x17c31)
#2 0x7fd0a9487394 in lp_symphony_solve …
```

TestDesign 1.2.2

---

.gitignore
DESCRIPTION
NEWS.md
R/constraint_functions.R
R/plot_functions.R
R/print_functions.R
R/shadow_functions.R
README.Rmd
README.md
cran-comments.md
inst/shiny/server.r
man/plot-methods.Rd
tests/testthat/test_exposure_methods.R
tests/testthat/test_plot_functions.r

* `plot()` now works better with 'knitr' markdown documents. This is enabled by removing the use of `recordPlot()` inside `plot()`. As a result, `p <- plot()` will not work anymore. Use `recordPlot()` for assigning plots into objects.
* Shiny app `TestDesign()` is updated to work with the above change.
* `plot()` gains a new `use_par` argument to override using default graphical parameters that are hard-coded into the function. This allows for more flexible formatting.
* `theta_segment` argument in `plot(type = "exposure")` is renamed to `theta_type`. The existing argument is deprecated and using it will raise a warning.
* added validation check for test length constraints. In shadow test approach, test length is expected to be a fixed value.

make plot() more flexible, validate test length constraint

---

NEWS.md
R/other_functions.R
R/shadow_class.R
R/shadowtest_functions.R
R/static_class.R
R/xdata_functions.R
man/createShadowTestConfig.Rd

- Added a new option for configuring how excluded items are treated. For this, `config_Shadow` and `createShadowTestConfig()` gain a new `exclude_policy` slot.
- `create*Config()` functions now explicitly raise an error when values are present in undefined/unused slot names.

add soft exclusion option

---

DESCRIPTION
NEWS.md
cran-comments.md

* `config_Shadow` and `createShadowTestConfig()` gain a new slot `exclude_policy` for configuring how excluded items are treated. Excluded items are supplied through the `exclude` argument in `Shadow()`.
* Shiny app `TestDesign()` gains a 'close app' button.
* Fixed where the Shiny app was not starting normally.
* Fixed where attempting to use an exposure acceleration factor greater than 1 in set-based adaptive assembly using `Shadow()` would trigger a 'incorrect number of subscripts' error.

TestDesign 1.3.2

---

_pkgdown.yml

- `pkgdown` page build was failing after #120.
- This was because the new function `makeSimulationDataCache` and the new class `simulation_data_cache-class` introduced in #120 were not listed in `_pkgdown.yml`, which is the index file used to build `pkgdown` pages. 
- `pkgdown` expects all classes and functions to be listed in `_pkgdown.yml`, regardless of whether they are `@export`ed or not.
- This fix adds `makeSimulationDataCache` and `simulation_data_cache-class` as internal entries in `_pkgdown.yml`.

fix pkgdown not building

---

.github/workflows/r.yml
.github/workflows/r_other_branches.yml
DESCRIPTION
tests/testthat/test_unidimensional.r

- Added codetests for item response and information functions for all item models. Codetest uses `mirtCAT` package for comparison.

add codetests for item response and information

---

NEWS.md
R/eligibility_functions.R
R/other_functions.R

- Fixed where `M` value was being ignored for exposure control even when it was supplied. (#134)
- The cause of the error was that `getConstants()` was not populating `$M`, and therefore `constants$M` was always `NULL` in `applyEligibilityConstraintsToInfo()`.
- `constants$max_info` had no other uses than as a fallback value of `M`, and thus was removed.

fix `M` being ignored even when it was supplied

---

NEWS.md
R/other_functions.R
R/shadow_functions.R

- Fixed where `Shadow()` was not working when the `FIXED` item selection method was used with a single `$fixed_theta` value in the config. (#132)
- The supplied `$fixed_theta` value is now used as-is, instead of being approximated to the nearest theta quadrature. This value is only utilized once in the beginning of `Shadow()` to precompute information, so this change does not affect the main simulation.

fix `Shadow()` to work when `FIXED` item selection is used

---

R/bayes_functions.R
R/other_functions.R

- Theta quadratures used for internal computation are now typecasted to a matrix, with the number of rows being the number of quadratures.
- This was done to prepare for multidimensional cases.

use matrix theta quadratures

---

R/other_functions.R
R/shadow_functions.R
R/theta_functions.R
tests/testthat/test-gfi.R
tests/testthat/test-refresh-methods.R
tests/testthat/test-theta-methods.R

- Interim thetas are now internally typecasted to a matrix, with the number of rows being the number of theta values (= test length).
- This was done to prepare for multidimensional cases.

use matrix interim theta

---

NEWS.md
R/theta_functions.R

- Fixed where EAP shrinkage correction was ignoring prior standard deviation even when it was supplied. This was due to incorrect parsing of the config object; it was attempting to parse `config_theta$prior_sd` which is an unused slot.

fix shrinkage correction

---

NEWS.md
R/theta_functions.R

- Fixed #143
- The cause of the bug was that `ipar_fence$ID` created inside `mlef()` was being typecasted to a factor, a default behavior in R <= 3.6.

fix `duplicate item IDs found` warning when using `MLEF` for R <= 3.6

---

NEWS.md
R/bayes_functions.R
R/other_functions.R
R/shadow_functions.R
R/theta_functions.R
tests/testthat/test_include_items_for_estimation.R

- fixed #150 
- refactored theta estimation logic to keep track of the posterior/likelihood vectors along with the point estimate
- added codetest for `include_items_for_estimation`
- adding error bars for initial theta estimate will be done in a separate PR

refactor the use of posterior density vector in theta estimation logic

---

DESCRIPTION
NEWS.md
R/solver_functions.R
cran-comments.md

- Fixed where `gurobi` version `10.0.0` was raising an 'unused argument' error.
- This error was due to the `env` argument of `gurobi()` being removed in the solver package version `10.0.0`.

fix where using `gurobi` version `10.0.0` was raising an 'unused argument' error

---

.github/workflows/r.yml
DESCRIPTION
NEWS.md
R/import.R
R/partitioning_functions.r
R/shadow_class.R
R/solver_functions.R
R/static_class.R
cran-comments.md
inst/shiny/global.r
inst/shiny/server.r
man/Split-methods.Rd
man/createShadowTestConfig.Rd
man/createStaticTestConfig.Rd
man/testSolver.Rd
tests/testthat/test_excluding.R
vignettes/rsymphony.Rmd

- Removed support for the `lpsymphony` solver because of installation issues in some systems. Users may use the `Rsymphony` solver as an alternative.

remove `lpsymphony` support

---

DESCRIPTION
NEWS.md
R/constraints_operators.R
R/eligibility_functions.R
README.Rmd
README.md
tests/testthat/test_combine_constraints.r

- Fixed where combining `constraints` objects was not resulting in combined constraints: #160
- Added codetests for the above.
- Combining `constraints` objects no longer complains about the 'CONSTRAINT' column being ignored.
- Removed a duplicate definition for `getEligibleFlagInSegment()`.
- Removed `Date` field from `DESCRIPTION`: CRAN generates this on their own, and this is not needed our side. See https://github.com/r-lib/devtools/issues/1327

fix combining `constraints` objects

---

NEWS.md
R/bayes_functions.R
R/shadow_functions.R
R/theta_functions.R

fix where final theta estimation with EAP incorrectly uses the first examinee's final theta priors for all examinees

---

NEWS.md
R/partitioning_functions.r
tests/testthat/test_partitioning_methods.r

- Fixed #162
- This was a postprocessing error where the raw solver solution is converted to item/set indices.
- Added codetests for the above.

fix where `Split()` returns set indices even when the pool is all discrete items

---

src/Makevars
src/Makevars.win

- The proper way to link to BLAS is like this (see [WRE section 1.2.1](https://cran.r-project.org/doc/manuals/R-exts.html#Using-Makevars)).
- This fixes the macos cross compilation: https://github.com/r-universe/choi-phd/actions/runs/7576934286/job/20636902845

fix MacOS cross builds

---

NEWS.md
R/partitioning_functions.r
man/Split-methods.Rd
tests/testthat/test_partitioning_methods.r

- Added a feature we have been discussing for a long time; added a new argument `n_maximum_partitions_per_item` to `Split()`. This allows the function to assemble partitions in a way that each item is allowed to be assigned to multiple partitions. The existing case of assembling all partitions to be mutually exclusive is equivalent to `n_maximum_partitions_per_item = 1` (default).
- If the assembly is set-based, each set will be allowed to be assigned to multiple partitions.
- Added codetests for this.
- Simplified codetests for `Split()` to use smaller tasks.

`Split()`: add a new argument `n_maximum_partitions_per_item` 

---

R/exposure_control_functions.R

- Added a note describing the `j` subscript should not be removed.
- ~~Updated the naming scheme for exposure record lists to not use the `j` subscript. Having the `j` subscript is misleading because the actual stored data is not examinee-wise data.~~
- ~~Added functions to make this change backwards compatible. When an old format input is detected, `Shadow()` will inform the user and update the input to the current version.~~
- ~~Added codetests for this.~~

added notes to not remove `j` subscripts in exposure record

---

DESCRIPTION
NEWS.md
R/helper_functions.R
cran-comments.md
man/getSolution-methods.Rd

- Fixed a markup error in the documentation of `getSolution()`, as informed by CRAN.
- For some reason this was not picked up in local checks (Windows, Mac).

fix markup error in `getSolution()` documentation

---

DESCRIPTION
inst/shiny/server.r

- Fixed where the Shiny app `TestDesign()` was not generating plots for the specified examinee ID.

fix Shiny app `TestDesign()` to generate examinee-wise plots correctly

---

.github/workflows/pkgdown.yml
.github/workflows/r.yml
DESCRIPTION
inst/shiny/server.r
inst/shiny/styles.css
inst/shiny/ui.r

- Fixed Shiny app where using the info range button without data loaded would crash the app.
- Updated CI settings to not include R 3.6 in buildtesting.
- Buildtesting on R 3.6 is no longer possible because some dependencies now require R >= 4.0 and thus cannot be installed on R 3.6.
- Increased R version requirement to >= 4.0.

fix Shiny app `TestDesign()` where using the info range button without data loaded would crash the app

---

R/other_functions.R

- Fixed where using `FIXED` item selection method would result in the following error:
```
Error in info[eligibility_flag_in_current_theta_segment$i == 0] - simulation_constants$exposure_M : 
non-numeric argument to binary operator
```
- This error was being caused by the information list being created in an unintended format.

fix getInfoFixedTheta()

---

R/helper_functions.R

- Updated orphaned function `countConstraints()` to call `getSolutionAttributes()` which has same but better functionality (is able to do the tallying for more types of constraints)
- `countConstraints()` is currently not being called anywhere, but it was retained previously.

`countConstraints()`: pass onto `getSolutionAttributes()`

---

R/plot_functions.R
R/shadow_functions.R
tests/testthat/test_overlap_control.r

- `Shadow()` now populates `cumulative_usage_matrix` in the first run as well.
- This change is meant to allow the validation in `plot(type = "overlap")` to be able to detect whether the input is a first run.
- Added codetests for overlap control.

update overlap control

---

R/partitioning_functions.r

- Fixed where `Split()` was sometimes parsing solution indices incorrectly.

`Split()`: fix solution parsing
