- DESCRIPTION
- NEWS.md
- R/shadow_functions.R
- cran-comments.md
- man/plotExposure-methods.Rd
* Add `\donttest` to the examples in `plotExposureRateFinal` and `plotExposure-method`.
> Add \donttest to some examples

- NEWS.md
- R/shadow_functions.R
- R/xdata_functions.R
- man/Shadow-methods.Rd
- tests/testthat/test_item_exclusion.R
* add a new argument `excluded_items` to `Shadow()`
* * the argument accepts a list containing item names for each examinee
* * specified items will be excluded from selection
> add excluded_items to Shadow

- .Rbuildignore
- .github/workflows/r_other_branches.yml
- .gitignore
- DESCRIPTION
- NEWS.md
- R/theta_functions.R
- cran-comments.md
* Streamlined `eap()` to handle input formats consistently with `mle()`. This should only affect use cases where `eap()` is called directly.
> TestDesign 1.2.5

- _pkgdown.yml
- pkgdown/extra.css
- by adding missing topics as internal topics
> fix pkgdown warnings

- NEWS.md
- R/eligibility_functions.R
- R/exposure_control_functions.R
* Fixed where alpha adjustment for exposure control was being applied excessively.
> Fix alpha correction mechanism

- DESCRIPTION
- NEWS.md
- cran-comments.md
- vignettes/split.Rmd
- vignettes/split.Rmd.source
* update `DESCRIPTION`, `NEWS.md`, `cran-comments.md`
> TestDesign 1.3.0

- DESCRIPTION
- NEWS.md
- R/exposure_control_functions.R
- inst/shiny/server.r
- inst/shiny/ui.r
- tests/testthat/test_setbased_adaptive.r
* Shiny app `TestDesign()` gains a 'close app' button.
* Fixed where the Shiny app was not starting normally.
* Fixed where attempting to use an exposure acceleration factor greater than 1 in set-based adaptive assembly using `Shadow()` would trigger a 'incorrect number of subscripts' error.
> fix issues

- R/other_functions.R
- R/shadow_class.R
- R/theta_functions.R
- man/createShadowTestConfig.Rd
- `config_Shadow@interim_theta` gains a new slot `hand_scored_attribute`. This slot expects an item attribute name that tells each item is hand scored or not.
- If a hand scored item is administered to an examinee, the interim theta estimate is not updated; the previous interim theta estimate is reused instead. If this occurs for the first item for an examinee, the starting theta is used as the value to be reused.
- The designated item attribute is attempted to be normalized into `TRUE` and `FALSE` values. It will `stop()` if normalization fails.
- (Implementation detail) The `o$item_is_hand_scored` in `getConstants()` is used to make the designated attribute available to `estimateInterimTheta()`, because `estimateInterimTheta()` does not have access to the item attribute table.
``` …
```
> add hand scored attribute

- R/loading_functions.R
- Streamlined item parameter SE parse logic in `loadItemPool()`.
- This was done to prepare for parsing multidimensional item parameters, where the number of columns also need to account for the number of dimensions.
> `loadItemPool()`: refactor SE parse logic

- R/loading_functions.R
- Streamlined item parameter parse logic in `loadItemPool()`.
- This was done to prepare for parsing multidimensional item parameters, where the number of columns also need to account for the number of dimensions.
> `loadItemPool()`: refactor item parameter parse logic

- R/plot_functions.R
- `plot()` functions for `output_Shadow_all` and `output_Shadow` are reorganized to have `plotShadowAudit()` and `plotShadowChart()` as actual plotting functions, and `plot()` as dispatchers.
- This was done to prepare for adding more cases to plotting functions.
> reorganize plotting functions

- DESCRIPTION
- NEWS.md
- R/other_functions.R
- R/shadow_functions.R
- R/shadowtest_functions.R
- R/solver_functions.R
- R/xdata_functions.R
- cran-comments.md
- tests/testthat/test_mixed_adaptive.r
- Updated cpp specification to `C++17` to meet CRAN requirement.
- Refactored `runAssembly()`.
- Refactored the item selection module from a shadow test.
- Added codetest for a mixed-discrete item pool.
> update cpp specification to `C++17`

- NEWS.md
- R/constraint_functions.R
- R/eligibility_functions.R
- R/exposure_control_functions.R
- R/helper_functions.R
- R/loading_functions.R
- R/other_functions.R
- R/shadow_functions.R
- R/shadowtest_functions.R
- R/xdata_functions.R
- tests/testthat/test_refresh_methods.R
- Renamed local variables/functions in a way that generalizes "stimuli" to "groupings". This is intended to make it better accommodate adding other types of groupings in the future.
- Added codetest for stimulus-based refresh rule.
> Refactor the handling of set structure

- .github/workflows/r.yml
- DESCRIPTION
- cran-comments.md
- completed wrap-up tasks for CRAN submission.
> wrap up for TestDesign 1.6.0

- .github/workflows/pkgdown.yml
- Fixed workflow configurations for pkgdown.
> fix pkgdown workflow

- R/eligibility_functions.R
- R/other_functions.R
- R/plot_functions.R
- R/shadow_class.R
- R/shadow_functions.R
- man/createShadowTestConfig.Rd
- man/flagIneligible.Rd
- added additional overlap control method, "ELIGIBILITY"
- streamlined `plotShadowOverlap()`
- `config_Shadow` gains a new argument in `overlap_control`: `max_overlap_rate`
> Update item overlap control

- R/other_functions.R
- R/shadow_class.R
- R/theta_functions.R
- Refactored the routine for customizing first segments.
> refactor first segment customization

- DESCRIPTION
- R/import.R
- R/shadow_class.R
- R/solver_functions.R
- R/static_class.R
- inst/shiny/global.r
- inst/shiny/server.r
- man/createShadowTestConfig.Rd
- man/createStaticTestConfig.Rd
- man/testSolver.Rd
- Added basic support for `highs` solver.
- `highs` is open source, and is fast enough for set-based assembly simulations.
- See here for introduction: https://highs.dev/
> add support for `highs` solver

- R/partitioning_class.r
- R/partitioning_functions.r
- R/shadow_class.R
- R/shadow_functions.R
- R/static_class.R
- R/static_functions.R
- man/output_Shadow_all-class.Rd
- man/output_Split-class.Rd
- man/output_Static-class.Rd
- Added function call records to main output objects.
- The output of `Shadow()` now includes simulation constants list.
> add function calls to main output objects

- DESCRIPTION
- R/bayes_functions.R
- R/calculate_adaptivity_measures.r
- R/plot_functions.R
- R/print_functions.R
- R/shadow_class.R
- R/static_class.R
- man/calculateAdaptivityMeasures.Rd
- man/createShadowTestConfig.Rd
- man/createStaticTestConfig.Rd
- changed the default solver to `highs`
- refactoring on `plot()`, `calculateAdaptivityMeasures()`, `parsePriorParameters()`
> Perform minor refactoring
